import type { Metadata } from "next";
import { Inter } from "next/font/google";
import localFont from 'next/font/local'
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
const vinila = localFont({
  src : [{
    path: '../public/fonts/VinilaTest-ExtendedExtrabold.otf'
  }],
  variable : '--font-vinila'
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${vinila.variable} ${inter.className}`}>
        <main className='mx-10'>
          {children}
        </main>
      </body>
    </html>
  );
}
